<?php
function dupree_vebra_filter_block_info() {
  	$blocks = array();
	$blocks['my_block'] = array(
    		'info' => t('Dupree Creative dupree_vebra_filter'),
  	);
 
  	return $blocks;
}

function dupree_vebra_filter_block_view($delta='') {

  	$block = array();
 
  	switch($delta) {
    		case 'my_block' :
      		$block['content'] = dupree_vebra_filter_view();
      		break;
 	 }
 
  	return $block;
}
